# Generated by Django 3.1.1 on 2021-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reactions',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('reactant1', models.CharField(max_length=10)),
                ('rcoe1', models.IntegerField()),
                ('reactant2', models.CharField(max_length=10)),
                ('rcoe2', models.IntegerField()),
                ('product1', models.CharField(max_length=10)),
                ('product21', models.CharField(max_length=10)),
                ('pcoe1', models.IntegerField()),
            ],
        ),
    ]
